### ISSUE TITLE
I2CDeviceSynch for serial communications

### ISSUE THREAD

**Issue by Team14423** [FIRST-Tech-Challenge/FtcRobotController#63] opened 2020-12-20 21:31 UTC
Hi -

We are trying to implement PixyCam2, which uses I2C, but does not use registers. Is there a parameter we can send in for ireg that will cause read() and write() to behave like serial drivers, simply reading data off the port as it comes rather than listing a specific register?

If not, is this why people say to use LegoI2C mode? If so, do you know the register we use for that?

**Comment by FROGbots-4634** [comment] 2020-12-21 03:43
Duplicate of https://github.com/ftctechnh/ftc_app/issues/577

**Comment by Team14423** [comment] 2020-12-21 17:35
Awwww, I got so excited thinking it was fixed. So, there's no solution on this point?

**Comment by Windwoes** [comment] 2021-08-15 21:19
This will be fixed in the next version of the SDK.

**Comment by Team14423** [comment] 2021-08-15 21:22
Awesome - thank you!

**Comment by Windwoes** [comment] 2021-09-20 15:54
Fixed in v7.0

**Closed by Windwoes** 2021-09-20 15:54 UTC
